# Generated by Django 6.0.3 on 2026-04-07 01:18

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_first_name', models.CharField(default='', max_length=60)),
                ('account_last_name', models.CharField(default='', max_length=60)),
                ('account_starting_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            managers=[
                ('Accounts', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal')], max_length=10)),
                ('transaction_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('transaction_description', models.CharField(blank=True, default='', max_length=100)),
                ('transaction_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkbookApp.account')),
            ],
            managers=[
                ('Transactions', django.db.models.manager.Manager()),
            ],
        ),
    ]
