# Generated by Django 6.0.3 on 2026-04-07 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkbookApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='account_starting_balance',
            new_name='initial_deposit',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='account_last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_account',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_type',
            new_name='type',
        ),
    ]
