# Generated by Django 6.0.3 on 2026-04-03 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0078_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('entrees', 'entrees'), ('drinks', 'drinks'), ('treats', 'treats'), ('appetizers', 'appetizers')], max_length=60),
        ),
    ]
