# Generated by Django 6.0.3 on 2026-04-07 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_first_name', models.CharField(default='', max_length=60)),
                ('account_last_name', models.CharField(default='', max_length=60)),
                ('account_starting_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Accounts',
            },
        ),
    ]
