# Generated by Django 6.0.3 on 2026-04-07 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accountApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('D', 'Deposit'), ('W', 'Withdrawal')], default='D', max_length=1)),
                ('transaction_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transaction_description', models.CharField(blank=True, default='', max_length=200)),
                ('transaction_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accountApp.account')),
            ],
            options={
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
