# Generated by Django 6.0.3 on 2026-04-06 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityCampus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_name', models.CharField(blank=True, default='', max_length=60)),
                ('campus_state', models.CharField(blank=True, default='', max_length=2)),
                ('campus_number', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name_plural': 'University Campus',
            },
        ),
    ]
